export const PRODUCT_IN_CART_GET = "PRODUCT_IN_CART_GET"
export const PRODUCT_IN_CART_CLEAR = "PRODUCT_IN_CART_CLEAR"
export const PRODUCT_IN_CART_ADD = "PRODUCT_IN_CART_ADD"
export const PRODUCT_IN_CART_REMOVE = "PRODUCT_IN_CART_REMOVE"